on:
  pull_request:
    branches: ["main"]

jobs:
  build-project:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: "**/obj/project.assets.json"
          key: dotnet-dependencies-${{ runner.os }}-${{ hashFiles('**/project.assets.json') }}
          restore-keys: |
            dotnet-dependencies-${{ runner.os }}-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore --no-incremental

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
